import type { DashboardState } from "./types.ts";

const startedAt = Date.now() - 11 * 60_000;

export const previewState: DashboardState = {
  session: {
    id: "sess_01JV0ID",
    agent: "claude-code",
    workspace: "payments-dev",
    transport: "stdio",
    posture: "enforce",
    startedAt,
  },
  health: {
    proxy: "healthy",
    upstream: "healthy",
    ledger: "verified",
    connector: "ready",
    latencyMs: 18,
  },
  ledger: {
    entries: 12_482,
    verifiedThrough: 12_482,
    head: "sha256:9c82...47fa",
    keyId: "dev-ed25519:a41c9d70",
    checkpointAgeSeconds: 14,
  },
  calls: [
    {
      id: "call_7fs1",
      time: "14:07:31",
      tool: "postgres.row.update",
      connector: "postgres",
      agent: "claude-code",
      workspace: "payments-dev",
      class: "r0",
      decision: "allow",
      status: "sealed",
      stage: "seal",
      blastRadius: 1,
      policyRule: "allow-keyed-updates",
      durationMs: 21,
      inverse: "postgres.row.update",
      compensation: null,
      snapshotRef: "customer://void/call_7fs1",
      ledgerHash: "sha256:7f19...a182",
      reason: "keyed before image captured",
    },
    {
      id: "call_8kd2",
      time: "14:07:36",
      tool: "aws.s3.object.delete",
      connector: "s3",
      agent: "claude-code",
      workspace: "payments-dev",
      class: "r1",
      decision: "allow",
      status: "sealed",
      stage: "seal",
      blastRadius: 3,
      policyRule: "allow-versioned-delete",
      durationMs: 44,
      inverse: "aws.s3.delete_marker.remove",
      compensation: null,
      snapshotRef: "s3://customer-void/snap-8kd2",
      ledgerHash: "sha256:87b4...b220",
      reason: "versioning enabled",
    },
    {
      id: "call_9pm4",
      time: "14:07:40",
      tool: "stripe.refund.create",
      connector: "stripe",
      agent: "claude-code",
      workspace: "payments-dev",
      class: "r2",
      decision: "hold",
      status: "pending",
      stage: "decide",
      blastRadius: 1,
      policyRule: "hold-money-movement",
      durationMs: 4,
      inverse: null,
      compensation: "stripe.refund.cancel if pending",
      snapshotRef: null,
      ledgerHash: null,
      reason: "money movement has no guaranteed inverse",
    },
    {
      id: "call_af31",
      time: "14:07:45",
      tool: "postgres.table.drop",
      connector: "postgres",
      agent: "claude-code",
      workspace: "payments-dev",
      class: "r3",
      decision: "deny",
      status: "cancelled",
      stage: "decide",
      blastRadius: 41_883,
      policyRule: "deny-destructive-ddl",
      durationMs: 2,
      inverse: null,
      compensation: null,
      snapshotRef: null,
      ledgerHash: "sha256:fe10...991c",
      reason: "destructive DDL is irreversible after commit",
    },
  ],
  holds: [],
  selectedCallId: "call_af31",
  paused: false,
  filter: "all",
};

export const previewHold = {
  call: previewState.calls[2]!,
  openedAt: Date.now() - 12_000,
  expiresAt: Date.now() + 78_000,
  approver: null,
} as const;
