/**
 * The structured precondition language, WP-04a.
 *
 * The registry's `when` strings are prose today, written the way an operator
 * would check the target by hand. Prose cannot be evaluated, so each case
 * gains an optional `if` in the structured form below while keeping the prose
 * for display, and the evaluator prefers the structured form when present.
 *
 * The grammar is deliberately closed. An unknown kind, an unknown operator or
 * an empty combinator is a load error rather than a guess, mirroring the
 * policy format's rule that a typo must never quietly widen a guard. That is
 * the property that lets a registry reviewer read an entry and know exactly
 * which facts and arguments decide its class.
 */

export type FactPrecondition = {
  kind: "fact";
  /** Declared fact name, for example "bucket.versioning". */
  fact: string;
  /** The value the fact must carry. Absent means "any non-empty value". */
  is?: string;
};

export type NotPrecondition = {
  kind: "not";
  of: Precondition;
};

export type ArgumentPrecondition = {
  kind: "argument";
  /** Argument name on the intercepted call, for example "versionId". */
  argument: string;
  operator: "present" | "absent" | "equals";
  value?: string;
};

export type AllPrecondition = {
  kind: "all";
  /** One or more; an empty list is a load error, not a trivially true guard. */
  of: readonly Precondition[];
};

export type AnyPrecondition = {
  kind: "any";
  of: readonly Precondition[];
};

export type Precondition =
  | FactPrecondition
  | NotPrecondition
  | ArgumentPrecondition
  | AllPrecondition
  | AnyPrecondition;

export const PRECONDITION_KINDS = [
  "fact",
  "not",
  "argument",
  "all",
  "any",
] as const;

/**
 * Structural validation without a schema dependency. The package imports
 * nothing, and this shape is small enough that hand written validation both
 * catches more (it names the path in the entry) and stays reviewable.
 */
export function validatePrecondition(value: unknown, path: string): string[] {
  const errors: string[] = [];
  if (typeof value !== "object" || value === null) {
    return [`${path}: a precondition must be an object`];
  }
  const record = value as Record<string, unknown>;
  const kind = record.kind;
  switch (kind) {
    case "fact": {
      if (typeof record.fact !== "string" || record.fact === "")
        errors.push(`${path}.fact: a fact name is required`);
      if (record.is !== undefined && typeof record.is !== "string")
        errors.push(`${path}.is: must be a string when present`);
      const extra = Object.keys(record).filter((k) => !["kind", "fact", "is"].includes(k));
      if (extra.length > 0) errors.push(`${path}: unknown key ${extra.join(", ")}`);
      break;
    }
    case "not": {
      if (record.of === undefined) errors.push(`${path}.of: required`);
      else errors.push(...validatePrecondition(record.of, `${path}.of`));
      const extra = Object.keys(record).filter((k) => !["kind", "of"].includes(k));
      if (extra.length > 0) errors.push(`${path}: unknown key ${extra.join(", ")}`);
      break;
    }
    case "argument": {
      if (typeof record.argument !== "string" || record.argument === "")
        errors.push(`${path}.argument: an argument name is required`);
      if (
        record.operator !== "present" &&
        record.operator !== "absent" &&
        record.operator !== "equals"
      )
        errors.push(`${path}.operator: must be present, absent or equals`);
      if (record.operator === "equals" && typeof record.value !== "string")
        errors.push(`${path}.value: required when the operator is equals`);
      const allowed = ["kind", "argument", "operator", "value"];
      const extra = Object.keys(record).filter((k) => !allowed.includes(k));
      if (extra.length > 0) errors.push(`${path}: unknown key ${extra.join(", ")}`);
      break;
    }
    case "all":
    case "any": {
      if (!Array.isArray(record.of) || record.of.length === 0)
        errors.push(`${path}.of: a combinator needs at least one precondition`);
      else
        record.of.forEach((item, index) =>
          errors.push(...validatePrecondition(item, `${path}.of[${index}]`)),
        );
      const extra = Object.keys(record).filter((k) => !["kind", "of"].includes(k));
      if (extra.length > 0) errors.push(`${path}: unknown key ${extra.join(", ")}`);
      break;
    }
    default:
      errors.push(
        `${path}.kind: must be one of ${PRECONDITION_KINDS.join(", ")}, got ${JSON.stringify(kind)}`,
      );
  }
  return errors;
}

/**
 * Depth bound for hostile hand written data. The registry is generated by
 * people, but the evaluator is a library that anything can call, and a
 * self referencing precondition is a stack overflow wearing a config file's
 * coat. A real entry never nests deeper than three.
 */
const MAX_DEPTH = 32;

export function holds(
  precondition: Precondition,
  facts: Readonly<Record<string, string | boolean | undefined>>,
  args: Readonly<Record<string, unknown>>,
  depth = 0,
): boolean {
  if (depth > MAX_DEPTH)
    throw new TypeError("precondition nests deeper than 32 levels");
  switch (precondition.kind) {
    case "fact": {
      const value = facts[precondition.fact];
      if (precondition.is === undefined)
        return value === true || (typeof value === "string" && value !== "");
      return value === precondition.is;
    }
    case "not":
      return !holds(precondition.of, facts, args, depth + 1);
    case "argument": {
      const value = args[precondition.argument];
      switch (precondition.operator) {
        case "present":
          return value !== undefined && value !== null;
        case "absent":
          return value === undefined || value === null;
        case "equals":
          return String(value) === precondition.value;
      }
      return false;
    }
    case "all":
      return precondition.of.every((item) => holds(item, facts, args, depth + 1));
    case "any":
      return precondition.of.some((item) => holds(item, facts, args, depth + 1));
  }
}
